### ISSUE TITLE
Why is this useless?

### ISSUE THREAD

**Issue by benfoxall** [mshick/rollup-plugin-env#2]
From the readme:

> Actually sort of useless. I put this together before I figured some bits of build process out.

I'd love to know what bits you figured out that made this useless. (I'd arrived here thinking this is exactly what I need)

**Comment by mshick** [comment]
@benfoxall Sure, good question!

It's not particularly useful (to my mind) because faking a `process` global for a browser was a hack for dealing with something like `process.env.NODE_ENV`, where I'm trying to set a switch based on environment. 

I originally created this plugin for working with React, and I had a problem like this https://github.com/rollup/rollup/issues/487. Ultimately I think, just as that thread suggests, `rollup-plugin-replace` is a better solution.

```
rollup({
  entry: 'main.js',
  plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify( 'production' )
    })
  ]
}).then(...)
```

If you really need the process global in some form, then maybe [rollup-plugin-node-globals](https://github.com/calvinmetcalf/rollup-plugin-node-globals) would be for you. It's going to be more comprehensive than this module.

**Comment by benfoxall** [comment]
@mshick ah, thanks for that! That's useful to know (`rollup-plugin-replace` will work fine for my needs).

**Comment by halfnibble** [comment]
For some reason, the `rollup-plugin-replace` solution increased my build time by 26%. A painful amount.

**Comment by Guria** [comment]
`rollup-plugin-replace` works not as expected for providing `env`. it only replaces exact strings and wouldn't work with `process.env['NODE_ENV']`. Has anyone met `webpack-define-plugin` analog for rollup?

**Comment by iFwu** [comment]
> `rollup-plugin-replace` works not as expected for providing `env`. it only replaces exact strings and wouldn't work with `process.env['NODE_ENV']`. Has anyone met `webpack-define-plugin` analog for rollup?

@Guria I use babel's transform-define plugin

**Comment by scottc-netflix** [comment]
Every solution I've found to this problem also massively increases build time. rollup-plugin-node-globals fixes the issue most reliably, but also doubles build time! Seems like this should be a simple string prepend to inject some globals and IMHO should be included in rollup by default.
